Is $\begin{bmatrix}1 \\3\end{bmatrix}$ is an eigenvector of $\begin{bmatrix}1 & -1\\6 &-4 \end{bmatrix}$? If so, what is the eigenvalue?


In [1]:
# Import library used
import numpy as np

In [2]:
# Initialization A variabel
A = np.array([
    [1,-1],
    [6,-4]
])
A

array([[ 1, -1],
       [ 6, -4]])

In [3]:
# Proof yes or not
np.array([1,3]) / np.linalg.norm(np.array([1,3]))

array([0.31622777, 0.9486833 ])

In [4]:
# Looking for eigenvalue values
np.linalg.eig(A)

(array([-1., -2.]),
 array([[0.4472136 , 0.31622777],
        [0.89442719, 0.9486833 ]]))

In [5]:
eigVals, eigVecs = np.linalg.eig(A)

In [6]:
eigVecs

array([[0.4472136 , 0.31622777],
       [0.89442719, 0.9486833 ]])

In [7]:
eigVals

array([-1., -2.])

In [8]:
eigVals[1]

-2.0

In [9]:
eigVecs[1]

array([0.89442719, 0.9486833 ])

$\begin{bmatrix}1 \\3\end{bmatrix}$ is an eigenvector of $\begin{bmatrix}1 & -1\\6 &-4 \end{bmatrix}$ = True
