In [2]:
import numpy as np

In [10]:
A = np.array([
    [1,-1],
    [6, 4]
])
A

array([[ 1, -1],
       [ 6,  4]])

Apakah [1,3] adalah eigenvector dari [[1, −1],[6, 4]] ? 
Jika Iya, berapakah eigenvalue-nya?


In [11]:
np.linalg.eig(A)

(array([2.5+1.93649167j, 2.5-1.93649167j]),
 array([[ 0.23145502-0.29880715j,  0.23145502+0.29880715j],
        [-0.9258201 +0.j        , -0.9258201 -0.j        ]]))

In [13]:
eigVals, eigVecs = np.linalg.eig(A)

In [14]:
eigVecs

array([[ 0.23145502-0.29880715j,  0.23145502+0.29880715j],
       [-0.9258201 +0.j        , -0.9258201 -0.j        ]])

In [15]:
eigVals

array([2.5+1.93649167j, 2.5-1.93649167j])

In [16]:
eigVals[1]

(2.5-1.9364916731037083j)

In [17]:
eigVecs[1]

array([-0.9258201+0.j, -0.9258201-0.j])